# Generated by Django 4.2.24 on 2025-09-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_new',
        ),
    ]
