# Generated by Django 4.2.24 on 2025-09-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_product_price_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('image', models.CharField(max_length=200)),
                ('specs', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accessory')),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accessory')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accessorycolor')),
            ],
        ),
        migrations.AddField(
            model_name='accessory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app.accessorycategory'),
        ),
        migrations.CreateModel(
            name='AccessoryCompatibleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.accessory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'unique_together': {('accessory', 'product')},
            },
        ),
    ]
